# This is an example configuration for an ESPHome firmware to measure the
# current power and overall energy consumption using an analog Ferraris
# electricity meter

# generic configuration (to be adapted)
esphome:
  name: ferraris-meter
  friendly_name: Stromzähler

# example ESP8266 firmware (can be replaced by appropriate configuration)
esp8266:
  board: esp01_1m

# include Ferraris component (mandatory)
external_components:
  - source: github://jensrossbach/esphome-ferraris-meter
    components: [ferraris]

# enable logging (optional)
logger:
  level: INFO

# enable Home Assistant API (mandatory if used with Home Assistant, alternatively configure MQTT)
api:
  encryption:
    key: !secret ha_api_key

# enable over-the-air updates (recommended)
ota:
  - platform: esphome
    password: !secret ota_password

# enable Wi-Fi (mandatory)
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # enable fallback hotspot (captive portal) in case Wi-Fi connection fails
  ap:
    ssid: Ferraris Meter Fallback Hotspot
    password: !secret fallback_hs_password

# needed for fallback hotspot (see above)
captive_portal:

# Ferraris component (mandatory)
ferraris:
  pin: GPIO4
  rotations_per_kwh: 75
  low_state_threshold: 400  # milliseconds
  energy_start_value: last_energy_value

# numeric sensors
sensor:
  - platform: ferraris
    power_consumption:
      name: Momentanverbrauch
    energy_meter:
      name: Verbrauchszähler
  - platform: wifi_signal
    name: Wi-Fi Signal
    update_interval: 60s

# binary sensors
binary_sensor:
  - platform: ferraris
    rotation_indicator:
      name: Umdrehungsindikator
  - platform: status
    name: Status

# text sensors
text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Adresse

# number components
number:
  - platform: ferraris
    energy_target_value:
      name: Verbrauchszähler-Zielwert
  - platform: homeassistant
    id: last_energy_value
    entity_id: input_number.stromzaehler_letzter_wert

# switch components
switch:
  - platform: ferraris
    calibration_mode:
      name: Kalibrierungsmodus

# button components
button:
  - platform: ferraris
    set_energy_meter:
      name: Verbrauchszähler überschreiben
